// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuCyEFlT_jqgU2q4_5Li-Y5xijKw5nZi8',
    appId: '1:661172740060:web:b123882553dfd4d7d2f919',
    messagingSenderId: '661172740060',
    projectId: 'kroki-92410',
    authDomain: 'kroki-92410.firebaseapp.com',
    storageBucket: 'kroki-92410.firebasestorage.app',
    measurementId: 'G-CGRTQBBJRX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3Wa-v33Bv7uEvjd2p2fJvmaVOf94KKbA',
    appId: '1:661172740060:android:824a008c0d5f01f9d2f919',
    messagingSenderId: '661172740060',
    projectId: 'kroki-92410',
    storageBucket: 'kroki-92410.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5Bk373eGYqVANrvRGbi248-mVRQ438dk',
    appId: '1:661172740060:ios:c9a2bf25c4b4c5e4d2f919',
    messagingSenderId: '661172740060',
    projectId: 'kroki-92410',
    storageBucket: 'kroki-92410.firebasestorage.app',
    iosBundleId: 'com.noxstudio.kroki',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5Bk373eGYqVANrvRGbi248-mVRQ438dk',
    appId: '1:661172740060:ios:c9a2bf25c4b4c5e4d2f919',
    messagingSenderId: '661172740060',
    projectId: 'kroki-92410',
    storageBucket: 'kroki-92410.firebasestorage.app',
    iosBundleId: 'com.noxstudio.kroki',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDuCyEFlT_jqgU2q4_5Li-Y5xijKw5nZi8',
    appId: '1:661172740060:web:8e3a5423ab3c707ed2f919',
    messagingSenderId: '661172740060',
    projectId: 'kroki-92410',
    authDomain: 'kroki-92410.firebaseapp.com',
    storageBucket: 'kroki-92410.firebasestorage.app',
    measurementId: 'G-SCYQXFN7YV',
  );
}
